// ======================================================================
//
//   GNU GENERAL PUBLIC LICENSE
//   Version 3, 29 June 2007
//   copyright (C) 2020 - 2021 Quentin Gruber
//   copyright (C) 2021 - 2022 H1emu community
//
//   https://github.com/QuentinGruber/h1z1-server
//   https://www.npmjs.com/package/h1z1-server
//
//   Based on https://github.com/psemu/soe-network
// ======================================================================

import DataSchema from "h1z1-dataschema";
import { LZ4 } from "../../../utils/utils";
import { packVehicleReferenceData, parseVehicleReferenceData } from "./shared";
import { profileDataSchema } from "./shared";

const weaponDefinitionSchema: any[] = [
  {
    name: "WEAPON_DEFINITIONS",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "DATA",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "ID", type: "uint32", defaultValue: 0 },
          { name: "WEAPON_GROUP_ID", type: "uint32", defaultValue: 0 },
          { name: "FLAGS", type: "uint8", defaultValue: 0 },
          { name: "EQUIP_MS", type: "uint32", defaultValue: 0 },
          { name: "UNEQUIP_MS", type: "uint32", defaultValue: 0 },
          { name: "FROM_PASSIVE_MS", type: "uint32", defaultValue: 0 },
          { name: "TO_PASSIVE_MS", type: "uint32", defaultValue: 0 },
          { name: "XP_CATEGORY", type: "uint32", defaultValue: 0 },
          { name: "TO_IRON_SIGHTS_MS", type: "uint32", defaultValue: 0 },
          { name: "FROM_IRON_SIGHTS_MS", type: "uint32", defaultValue: 0 },
          { name: "TO_IRON_SIGHTS_ANIM_MS", type: "uint32", defaultValue: 0 },
          { name: "FROM_IRON_SIGHTS_ANIM_MS", type: "uint32", defaultValue: 0 },
          { name: "SPRINT_RECOVERY_MS", type: "uint32", defaultValue: 0 },
          { name: "NEXT_USE_DELAY_MSEC", type: "uint32", defaultValue: 0 },
          { name: "TURN_RATE_MODIFIER", type: "float", defaultValue: 0 },
          { name: "MOVEMENT_SPEED_MODIFIER", type: "float", defaultValue: 0 },
          { name: "PROPULSION_TYPE", type: "uint32", defaultValue: 0 },
          { name: "HEAT_BLEED_OFF_RATE", type: "uint32", defaultValue: 0 },
          { name: "HEAT_CAPACITY", type: "uint32", defaultValue: 0 },
          { name: "OVERHEAT_PENALTY_MS", type: "uint32", defaultValue: 0 },
          { name: "RANGE_STRING_ID", type: "uint32", defaultValue: 0 },
          {
            name: "MELEE_DETECT",
            type: "schema",
            defaultValue: {},
            fields: [
              { name: "MELEE_DETECT_WIDTH", type: "uint32", defaultValue: 0 },
              { name: "MELEE_DETECT_HEIGHT", type: "uint32", defaultValue: 0 },
            ],
          },
          { name: "ANIMATION_SET_NAME", type: "string", defaultValue: "" },
          { name: "VEHICLE_FIRST_PERSON_CAMERA_ID", type: "uint32", defaultValue: 0 },
          { name: "VEHICLE_THIRD_PERSON_CAMERA_ID", type: "uint32", defaultValue: 0 },
          { name: "OVERHEAT_EFFECT_ID", type: "uint32", defaultValue: 0 },
          { name: "MIN_PITCH", type: "float", defaultValue: 0 },
          { name: "MAX_PITCH", type: "float", defaultValue: 0 },
          { name: "AUDIO_GAME_OBJECT", type: "uint32", defaultValue: 0 },
          {
            name: "AMMO_SLOTS",
            type: "array",
            defaultValue: [],
            fields: [
              { name: "AMMO_ID", type: "uint32", defaultValue: 0 },
              { name: "CLIP_SIZE", type: "uint32", defaultValue: 0 },
              { name: "CAPACITY", type: "uint32", defaultValue: 0 },
              { name: "START_EMPTY", type: "boolean", defaultValue: 0 },
              { name: "REFILL_AMMO_PER_TICK", type: "uint32", defaultValue: 0 },
              { name: "REFILL_AMMO_DELAY_MS", type: "uint32", defaultValue: 0 },
              { name: "CLIP_ATTACHMENT_SLOT", type: "uint32", defaultValue: 0 },
              { name: "CLIP_MODEL_NAME", type: "string", defaultValue: "" },
              { name: "RELOAD_WEAPON_BONE", type: "string", defaultValue: "" },
              { name: "RELOAD_CHARACTER_BONE", type: "string", defaultValue: "" },
            ],
          },
          {
            name: "FIRE_GROUPS",
            type: "array",
            defaultValue: [],
            fields: [
              { name: "FIRE_GROUP_ID", type: "uint32", defaultValue: 0 },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "FIRE_GROUP_DEFINITIONS",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "DATA",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "ID", type: "uint32", defaultValue: 0 },
          {
            name: "unknownArray1",
            type: "array",
            defaultValue: [],
            fields: [
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
            ],
          },
          { name: "unknownByte1", type: "uint8", defaultValue: 0 },
          { name: "unknownDword1", type: "uint32", defaultValue: 0 },
          { name: "unknownDword2", type: "uint32", defaultValue: 0 },
          { name: "unknownDword3", type: "uint32", defaultValue: 0 },
          { name: "unknownDword4", type: "uint32", defaultValue: 0 },
          { name: "unknownDword5", type: "uint32", defaultValue: 0 },
          { name: "unknownDword6", type: "uint32", defaultValue: 0 },
          { name: "unknownDword7", type: "uint32", defaultValue: 0 },
          { name: "unknownDword8", type: "uint32", defaultValue: 0 },
          { name: "unknownDword9", type: "uint32", defaultValue: 0 },
          { name: "unknownDword10", type: "uint32", defaultValue: 0 },
        ],
      },
    ],
  },
  {
    name: "FIRE_MODE_DEFINITIONS",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "DATA",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "ID", type: "uint32", defaultValue: 0 },
          {
            name: "DATA",
            type: "schema",
            defaultValue: {},
            fields: [
              {
                name: "unknownBytes1",
                type: "schema",
                defaultValue: {},
                fields: [
                  { name: "unknownByte1", type: "uint8", defaultValue: 0 },
                  { name: "unknownByte2", type: "uint8", defaultValue: 0 },
                  { name: "unknownByte3", type: "uint8", defaultValue: 0 },
                ],
              },
              { name: "unknownByte1", type: "uint8", defaultValue: 0 },
              { name: "AMMO_ID", type: "uint32", defaultValue: 0 },
              { name: "unknownByte2", type: "uint8", defaultValue: 0 },
              { name: "unknownByte3", type: "uint8", defaultValue: 0 },
              { name: "unknownWord1", type: "uint16", defaultValue: 0 },
              { name: "unknownWord2", type: "uint16", defaultValue: 0 },
              { name: "unknownWord3", type: "uint16", defaultValue: 0 },
              { name: "unknownWord4", type: "uint16", defaultValue: 0 },
              { name: "unknownWord5", type: "uint16", defaultValue: 0 },
              { name: "unknownWord6", type: "uint16", defaultValue: 0 },
              { name: "unknownFloat1", type: "float", defaultValue: 0 },
              { name: "unknownByte4", type: "uint8", defaultValue: 0 },
              { name: "unknownWord7", type: "uint16", defaultValue: 0 },
              { name: "unknownWord8", type: "uint16", defaultValue: 0 },
              { name: "unknownWord9", type: "uint16", defaultValue: 0 },
              { name: "unknownWord10", type: "uint16", defaultValue: 0 },
              { name: "unknownWord11", type: "uint16", defaultValue: 0 },
              { name: "unknownByte5", type: "uint8", defaultValue: 0 },
              { name: "unknownFloat2", type: "float", defaultValue: 0 },
              { name: "unknownFloat3", type: "float", defaultValue: 0 },
              { name: "unknownFloat4", type: "float", defaultValue: 0 },
              { name: "unknownFloat5", type: "float", defaultValue: 0 },
              { name: "unknownFloat6", type: "float", defaultValue: 0 },
              { name: "unknownFloat7", type: "float", defaultValue: 0 },
              { name: "unknownFloat8", type: "float", defaultValue: 0 },
              { name: "unknownFloat9", type: "float", defaultValue: 0 },
              { name: "unknownFloat10", type: "float", defaultValue: 0 },
              { name: "unknownFloat11", type: "float", defaultValue: 0 },
              { name: "unknownFloat12", type: "float", defaultValue: 0 },
              { name: "unknownFloat13", type: "float", defaultValue: 0 },
              { name: "unknownWord12", type: "uint16", defaultValue: 0 },
              { name: "unknownFloat14", type: "float", defaultValue: 0 },
              { name: "unknownFloat15", type: "float", defaultValue: 0 },
              { name: "unknownByte6", type: "uint8", defaultValue: 0 },
              { name: "unknownFloat16", type: "float", defaultValue: 0 },
              { name: "unknownFloat17", type: "float", defaultValue: 0 },
              { name: "unknownFloat18", type: "float", defaultValue: 0 },
              { name: "unknownFloat19", type: "float", defaultValue: 0 },
              { name: "unknownFloat20", type: "float", defaultValue: 0 },
              { name: "unknownFloat21", type: "float", defaultValue: 0 },
              { name: "unknownWord13", type: "uint16", defaultValue: 0 },
              { name: "unknownFloat22", type: "float", defaultValue: 0 },
              { name: "unknownFloat23", type: "float", defaultValue: 0 },
              { name: "unknownFloat24", type: "float", defaultValue: 0 },
              { name: "unknownFloat25", type: "float", defaultValue: 0 },
              { name: "unknownFloat26", type: "float", defaultValue: 0 },
              { name: "unknownFloat27", type: "float", defaultValue: 0 },
              { name: "unknownFloat28", type: "float", defaultValue: 0 },
              { name: "unknownFloat29", type: "float", defaultValue: 0 },
              { name: "unknownFloat30", type: "float", defaultValue: 0 },
              { name: "unknownFloat31", type: "float", defaultValue: 0 },
              { name: "unknownWord14", type: "uint16", defaultValue: 0 },
              { name: "unknownWord15", type: "uint16", defaultValue: 0 },
              { name: "unknownWord16", type: "uint16", defaultValue: 0 },
              { name: "unknownWord17", type: "uint16", defaultValue: 0 },
              { name: "unknownFloat32", type: "float", defaultValue: 0 },
              {
                name: "unknownArray1",
                type: "schema",
                defaultValue: {},
                fields: [
                  { name: "unknownFloat1", type: "float", defaultValue: 0 },
                  { name: "unknownFloat2", type: "float", defaultValue: 0 },
                  { name: "unknownFloat3", type: "float", defaultValue: 0 },
                ],
              },
              { name: "unknownByte7", type: "uint8", defaultValue: 0 },
              { name: "unknownByte8", type: "uint8", defaultValue: 0 },
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
              { name: "unknownDword2", type: "uint32", defaultValue: 0 },
              { name: "unknownWord18", type: "uint16", defaultValue: 0 },
              {
                name: "unknownFloats1",
                type: "schema",
                defaultValue: {},
                fields: [
                  { name: "unknownFloat1", type: "float", defaultValue: 0 },
                  { name: "unknownFloat2", type: "float", defaultValue: 0 },
                ],
              },
              {
                name: "unknownFloats2",
                type: "schema",
                defaultValue: {},
                fields: [
                  { name: "unknownFloat1", type: "float", defaultValue: 0 },
                  { name: "unknownFloat2", type: "float", defaultValue: 0 },
                ],
              },
              { name: "unknownFloat33", type: "float", defaultValue: 0 },
              { name: "unknownFloat34", type: "float", defaultValue: 0 },
              { name: "unknownFloat35", type: "float", defaultValue: 0 },
              { name: "unknownFloat36", type: "float", defaultValue: 0 },
              { name: "unknownDword3", type: "uint32", defaultValue: 0 },
              { name: "unknownDword4", type: "uint32", defaultValue: 0 },
              { name: "unknownFloat37", type: "float", defaultValue: 0 },
              { name: "unknownFloat38", type: "float", defaultValue: 0 },
              { name: "unknownDword5", type: "uint32", defaultValue: 0 },
              { name: "unknownFloat39", type: "float", defaultValue: 0 },
              { name: "unknownDword6", type: "uint32", defaultValue: 0 },
              { name: "unknownDword7", type: "uint32", defaultValue: 0 },
              { name: "unknownDword8", type: "uint32", defaultValue: 0 },
              { name: "unknownByte9", type: "uint8", defaultValue: 0 },
              { name: "unknownByte10", type: "uint8", defaultValue: 0 },
              { name: "unknownFloat40", type: "float", defaultValue: 0 },
              { name: "unknownFloat41", type: "float", defaultValue: 0 },
              { name: "unknownFloat42", type: "float", defaultValue: 0 },
              { name: "unknownFloat43", type: "float", defaultValue: 0 },
              { name: "unknownDword9", type: "uint32", defaultValue: 0 },
              { name: "unknownDword10", type: "uint32", defaultValue: 0 },
              { name: "unknownFloat44", type: "float", defaultValue: 0 },
              { name: "unknownFloat45", type: "float", defaultValue: 0 },
              { name: "unknownFloat46", type: "float", defaultValue: 0 },
              { name: "unknownBoolean1", type: "boolean", defaultValue: false },
              { name: "unknownFloat47", type: "float", defaultValue: 0 },
              { name: "unknownFloat48", type: "float", defaultValue: 0 },
              { name: "unknownFloat49", type: "float", defaultValue: 0 },
              { name: "unknownFloat50", type: "float", defaultValue: 0 },
              { name: "unknownFloat51", type: "float", defaultValue: 0 },
              { name: "unknownFloat52", type: "float", defaultValue: 0 },
              { name: "unknownFloat53", type: "float", defaultValue: 0 },
              { name: "unknownBoolean2", type: "boolean", defaultValue: false },
              { name: "unknownFloat54", type: "float", defaultValue: 0 },
              { name: "unknownFloat55", type: "float", defaultValue: 0 },
              { name: "unknownFloat56", type: "float", defaultValue: 0 },
              { name: "unknownFloat57", type: "float", defaultValue: 0 },
              { name: "unknownFloat58", type: "float", defaultValue: 0 },
              { name: "unknownFloat59", type: "float", defaultValue: 0 },
              { name: "unknownFloat60", type: "float", defaultValue: 0 },
              { name: "unknownFloat61", type: "float", defaultValue: 0 },
              { name: "unknownFloat62", type: "float", defaultValue: 0 },
              { name: "unknownFloat63", type: "float", defaultValue: 0 },
              { name: "unknownFloat64", type: "float", defaultValue: 0 },
              { name: "unknownFloat65", type: "float", defaultValue: 0 },
              { name: "unknownFloat66", type: "float", defaultValue: 0 },
              { name: "unknownFloat67", type: "float", defaultValue: 0 },
              { name: "unknownFloat68", type: "float", defaultValue: 0 },
              { name: "unknownFloat69", type: "float", defaultValue: 0 },
              { name: "unknownFloat70", type: "float", defaultValue: 0 },
              { name: "unknownFloat71", type: "float", defaultValue: 0 },
              { name: "unknownFloat72", type: "float", defaultValue: 0 },
              { name: "unknownFloat73", type: "float", defaultValue: 0 },
              { name: "unknownFloat74", type: "float", defaultValue: 0 },
              { name: "unknownFloat75", type: "float", defaultValue: 0 },
              { name: "unknownFloat76", type: "float", defaultValue: 0 },
              { name: "unknownFloat77", type: "float", defaultValue: 0 },
              { name: "unknownFloat78", type: "float", defaultValue: 0 },
              { name: "unknownFloat79", type: "float", defaultValue: 0 },
              { name: "unknownFloat80", type: "float", defaultValue: 0 },
              { name: "unknownFloat81", type: "float", defaultValue: 0 },
              { name: "unknownFloat82", type: "float", defaultValue: 0 },
              { name: "unknownFloat83", type: "float", defaultValue: 0 },
              { name: "unknownFloat84", type: "float", defaultValue: 0 },
              { name: "unknownFloat85", type: "float", defaultValue: 0 },
              { name: "unknownFloat86", type: "float", defaultValue: 0 },
              { name: "unknownFloat87", type: "float", defaultValue: 0 },
              { name: "unknownFloat88", type: "float", defaultValue: 0 },
              { name: "unknownFloat89", type: "float", defaultValue: 0 },
              { name: "unknownFloat90", type: "float", defaultValue: 0 },
              { name: "unknownFloat91", type: "float", defaultValue: 0 },
              { name: "unknownFloat92", type: "float", defaultValue: 0 },
              { name: "unknownFloat93", type: "float", defaultValue: 0 },
              { name: "unknownFloat94", type: "float", defaultValue: 0 },
              { name: "unknownFloat95", type: "float", defaultValue: 0 },
              { name: "unknownFloat96", type: "float", defaultValue: 0 },
              { name: "unknownFloat97", type: "float", defaultValue: 0 },
              { name: "unknownBoolean3", type: "boolean", defaultValue: false },
              { name: "unknownDword11", type: "uint32", defaultValue: 0 },
              { name: "unknownBoolean4", type: "boolean", defaultValue: false },
              { name: "unknownFloat98", type: "float", defaultValue: 0 },
              { name: "unknownFloat99", type: "float", defaultValue: 0 },
              { name: "unknownFloat100", type: "float", defaultValue: 0 },
              { name: "unknownFloat101", type: "float", defaultValue: 0 },
              { name: "unknownFloat102", type: "float", defaultValue: 0 },
              { name: "unknownFloat103", type: "float", defaultValue: 0 },
              { name: "unknownFloat104", type: "float", defaultValue: 0 },
              { name: "unknownFloat105", type: "float", defaultValue: 0 },
              { name: "unknownFloat106", type: "float", defaultValue: 0 },
              { name: "unknownFloat107", type: "float", defaultValue: 0 },
              { name: "unknownFloat108", type: "float", defaultValue: 0 },
              { name: "unknownFloat109", type: "float", defaultValue: 0 },
              { name: "unknownBoolean5", type: "boolean", defaultValue: false },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "PLAYER_STATE_GROUP_DEFINITIONS",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      { name: "unknownDword1", type: "uint32", defaultValue: 0 },
      {
        name: "PLAYER_STATE_PROPERTIES",
        type: "array",
        defaultValue: [],
        fields: [
          { name: "GROUP_ID", type: "uint32", defaultValue: 0 },
          {
            name: "DATA",
            type: "schema",
            defaultValue: {},
            fields: [
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
              { name: "unknownByte1", type: "uint8", defaultValue: 0 },
              { name: "unknownFloat1", type: "float", defaultValue: 0 },
              { name: "unknownFloat2", type: "float", defaultValue: 0 },
              { name: "unknownFloat3", type: "float", defaultValue: 0 },
              { name: "unknownFloat4", type: "float", defaultValue: 0 },
              { name: "unknownDword2", type: "uint32", defaultValue: 0 },
              { name: "unknownDword3", type: "uint32", defaultValue: 0 },
              { name: "unknownFloat5", type: "float", defaultValue: 0 },
              { name: "unknownDword5", type: "uint32", defaultValue: 0 },
              { name: "unknownFloat6", type: "float", defaultValue: 0 },
              { name: "unknownFloat7", type: "float", defaultValue: 0 },
              { name: "unknownFloat8", type: "float", defaultValue: 0 },
              { name: "unknownFloat9", type: "float", defaultValue: 0 },
              { name: "unknownFloat10", type: "float", defaultValue: 0 },
              { name: "unknownDword5", type: "uint32", defaultValue: 0 },
              { name: "unknownFloat11", type: "float", defaultValue: 0 },
              { name: "unknownDword6", type: "uint32", defaultValue: 0 },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "FIRE_MODE_PROJECTILE_MAPPING_DATA",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "DATA",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "ID", type: "uint32", defaultValue: 0 },
          { name: "unknownDword2", type: "uint32", defaultValue: 0 },
          { name: "unknownDword3", type: "uint32", defaultValue: 0 },
        ],
      },
    ],
  },
  {
    name: "AIM_ASSIST_DEFINITIONS",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "DATA",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "unknownFloat1", type: "float", defaultValue: 0 },
          { name: "unknownFloat2", type: "float", defaultValue: 0 },
          { name: "unknownFloat3", type: "float", defaultValue: 0 },
          { name: "unknownFloat4", type: "float", defaultValue: 0 },
          { name: "unknownFloat5", type: "float", defaultValue: 0 },
          { name: "unknownFloat6", type: "float", defaultValue: 0 },
          { name: "unknownFloat7", type: "float", defaultValue: 0 },
          { name: "unknownFloat8", type: "float", defaultValue: 0 },
          { name: "unknownFloat9", type: "float", defaultValue: 0 },
          { name: "unknownFloat10", type: "float", defaultValue: 0 },
          { name: "unknownFloat11", type: "float", defaultValue: 0 },
          { name: "unknownFloat12", type: "float", defaultValue: 0 },
          { name: "unknownFloat13", type: "float", defaultValue: 0 },
          { name: "unknownFloat14", type: "float", defaultValue: 0 },
          { name: "unknownFloat15", type: "float", defaultValue: 0 },
          { name: "unknownFloat16", type: "float", defaultValue: 0 },
          { name: "unknownDword1", type: "uint32", defaultValue: 0 },
          { name: "unknownFloat19", type: "float", defaultValue: 0 },
          { name: "unknownFloat20", type: "float", defaultValue: 0 },
          { name: "unknownFloat21", type: "float", defaultValue: 0 },
          { name: "unknownFloat22", type: "float", defaultValue: 0 },
          { name: "unknownFloat23", type: "float", defaultValue: 0 },
          { name: "unknownFloat24", type: "float", defaultValue: 0 },
        ],
      },
    ],
  },
];

function packWeaponDefinitionData(obj: any) {
  let compressionData = Buffer.allocUnsafe(8);
  const data = DataSchema.pack(
    weaponDefinitionSchema,
    obj
  ).data,
  input = data;
  let output = Buffer.alloc(LZ4.encodeBound(input.length));
  output = output.slice(0, LZ4.encodeBlock(input, output));
  compressionData.writeUInt32LE(output.length, 0);
  compressionData.writeUInt32LE(data.length, 4);
  return Buffer.concat([compressionData, output]);
}

export const referenceDataPackets: any = [
  ["ReferenceData.ItemClassDefinitions", 0x1701, {}],
  ["ReferenceData.ItemCategoryDefinitions", 0x1702, {}],
  [
    "ReferenceData.ClientProfileData",
    0x1703,
    {
      fields: [
        {
          name: "profiles",
          type: "array",
          defaultValue: [],
          fields: profileDataSchema,
        },
      ],
    },
  ],
  [
    "ReferenceData.WeaponDefinitions",
    0x1704,
    {
      fields: [
        {
          name: "data",
          type: "byteswithlength",
          fields: [
            {
              name: "definitionsData",
              type: "custom",
              packer: packWeaponDefinitionData,
            },
          ],
        },
      ],
    },
  ],
  ["ReferenceData.ProjectileDefinitions", 0x1705, {}],
  [
    "ReferenceData.VehicleDefinitions",
    0x1706,
    {
      fields: [
        {
          name: "data",
          type: "custom",
          parser: parseVehicleReferenceData,
          packer: packVehicleReferenceData,
        },
      ],
    },
  ],
];
