// ======================================================================
//
//   GNU GENERAL PUBLIC LICENSE
//   Version 3, 29 June 2007
//   copyright (C) 2020 - 2021 Quentin Gruber
//   copyright (C) 2021 - 2022 H1emu community
//
//   https://github.com/QuentinGruber/h1z1-server
//   https://www.npmjs.com/package/h1z1-server
//
//   Based on https://github.com/psemu/soe-network
// ======================================================================

import DataSchema from "h1z1-dataschema";
import { LZ4 } from "../../../utils/utils";
import { packVehicleReferenceData, parseVehicleReferenceData } from "./shared";
import { profileDataSchema } from "./shared";

const weaponDefinitionSchema: any[] = [
  {
    name: "unknownArray1",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "unknownData1",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "unknownDword1", type: "uint32", defaultValue: 0 },
          { name: "unknownDword2", type: "uint32", defaultValue: 0 },
          { name: "unknownByte1", type: "uint8", defaultValue: 0 },
          { name: "unknownDword3", type: "uint32", defaultValue: 0 },
          { name: "unknownDword4", type: "uint32", defaultValue: 0 },
          { name: "unknownDword5", type: "uint32", defaultValue: 0 },
          { name: "unknownDword6", type: "uint32", defaultValue: 0 },
          { name: "unknownDword7", type: "uint32", defaultValue: 0 },
          { name: "unknownDword8", type: "uint32", defaultValue: 0 },
          { name: "unknownDword9", type: "uint32", defaultValue: 0 },
          { name: "unknownDword10", type: "uint32", defaultValue: 0 },
          { name: "unknownDword11", type: "uint32", defaultValue: 0 },
          { name: "unknownDword12", type: "uint32", defaultValue: 0 },
          { name: "unknownDword13", type: "uint32", defaultValue: 0 },
          { name: "unknownDword14", type: "uint32", defaultValue: 0 },
          { name: "unknownDword15", type: "uint32", defaultValue: 0 },
          { name: "unknownDword16", type: "uint32", defaultValue: 0 },
          { name: "unknownDword17", type: "uint32", defaultValue: 0 },
          { name: "unknownDword18", type: "uint32", defaultValue: 0 },
          { name: "unknownDword19", type: "uint32", defaultValue: 0 },
          { name: "unknownDword20", type: "uint32", defaultValue: 0 },
          {
            name: "unknownData1",
            type: "schema",
            defaultValue: {},
            fields: [
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
              { name: "unknownDword2", type: "uint32", defaultValue: 0 },
            ],
          },
          { name: "unknownString1", type: "string", defaultValue: "" },
          { name: "unknownDword21", type: "uint32", defaultValue: 0 },
          { name: "unknownDword22", type: "uint32", defaultValue: 0 },
          { name: "unknownDword23", type: "uint32", defaultValue: 0 },
          { name: "unknownDword24", type: "uint32", defaultValue: 0 },
          { name: "unknownDword25", type: "uint32", defaultValue: 0 },
          { name: "unknownDword26", type: "uint32", defaultValue: 0 },
          {
            name: "unknownArray1",
            type: "array",
            defaultValue: [],
            fields: [
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
              { name: "unknownDword2", type: "uint32", defaultValue: 0 },
              { name: "unknownDword3", type: "uint32", defaultValue: 0 },
              { name: "unknownBoolean1", type: "boolean", defaultValue: 0 },
              { name: "unknownDword4", type: "uint32", defaultValue: 0 },
              { name: "unknownDword5", type: "uint32", defaultValue: 0 },
              { name: "unknownDword6", type: "uint32", defaultValue: 0 },
              { name: "unknownString1", type: "string", defaultValue: "" },
              { name: "unknownString2", type: "string", defaultValue: "" },
              { name: "unknownString3", type: "string", defaultValue: "" },
            ],
          },
          {
            name: "unknownArray2",
            type: "array",
            defaultValue: [],
            fields: [
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "unknownArray2",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "unknownData1",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "unknownDword1", type: "uint32", defaultValue: 0 },
          {
            name: "unknownArray1",
            type: "array",
            defaultValue: [],
            fields: [
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
            ],
          },
          { name: "unknownDword2", type: "uint32", defaultValue: 0 },
          { name: "unknownDword3", type: "uint32", defaultValue: 0 },
          { name: "unknownDword4", type: "uint32", defaultValue: 0 },
          { name: "unknownDword5", type: "uint32", defaultValue: 0 },
          { name: "unknownDword6", type: "uint32", defaultValue: 0 },
          { name: "unknownDword7", type: "uint32", defaultValue: 0 },
          { name: "unknownDword8", type: "uint32", defaultValue: 0 },
          { name: "unknownDword9", type: "uint32", defaultValue: 0 },
          { name: "unknownDword10", type: "uint32", defaultValue: 0 },
          { name: "unknownDword11", type: "uint32", defaultValue: 0 },
        ],
      },
    ],
  },
  {
    name: "unknownArray3",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "unknownData1",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "unknownDword1", type: "uint32", defaultValue: 0 },
          {
            name: "unknownData1",
            type: "schema",
            defaultValue: {},
            fields: [
              {
                name: "unknownBytes1",
                type: "schema",
                defaultValue: {},
                fields: [
                  { name: "unknownByte1", type: "uint8", defaultValue: 0 },
                  { name: "unknownByte2", type: "uint8", defaultValue: 0 },
                  { name: "unknownByte3", type: "uint8", defaultValue: 0 },
                ],
              },
              { name: "unknownByte1", type: "uint8", defaultValue: 0 },
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
              { name: "unknownByte2", type: "uint8", defaultValue: 0 },
              { name: "unknownByte3", type: "uint8", defaultValue: 0 },
              { name: "unknownWord1", type: "uint16", defaultValue: 0 },
              { name: "unknownWord2", type: "uint16", defaultValue: 0 },
              { name: "unknownWord3", type: "uint16", defaultValue: 0 },
              { name: "unknownWord4", type: "uint16", defaultValue: 0 },
              { name: "unknownWord5", type: "uint16", defaultValue: 0 },
              { name: "unknownWord6", type: "uint16", defaultValue: 0 },
              { name: "unknownDword2", type: "uint32", defaultValue: 0 },
              { name: "unknownByte4", type: "uint8", defaultValue: 0 },
              { name: "unknownWord7", type: "uint16", defaultValue: 0 },
              { name: "unknownWord8", type: "uint16", defaultValue: 0 },
              { name: "unknownWord9", type: "uint16", defaultValue: 0 },
              { name: "unknownWord10", type: "uint16", defaultValue: 0 },
              { name: "unknownWord11", type: "uint16", defaultValue: 0 },
              { name: "unknownByte5", type: "uint8", defaultValue: 0 },
              { name: "unknownDword3", type: "uint32", defaultValue: 0 },
              { name: "unknownDword4", type: "uint32", defaultValue: 0 },
              { name: "unknownDword5", type: "uint32", defaultValue: 0 },
              { name: "unknownDword6", type: "uint32", defaultValue: 0 },
              { name: "unknownDword7", type: "uint32", defaultValue: 0 },
              { name: "unknownDword8", type: "uint32", defaultValue: 0 },
              { name: "unknownDword9", type: "uint32", defaultValue: 0 },
              { name: "unknownDword10", type: "uint32", defaultValue: 0 },
              { name: "unknownDword11", type: "uint32", defaultValue: 0 },
              { name: "unknownDword12", type: "uint32", defaultValue: 0 },
              { name: "unknownDword13", type: "uint32", defaultValue: 0 },
              { name: "unknownDword14", type: "uint32", defaultValue: 0 },
              { name: "unknownWord12", type: "uint16", defaultValue: 0 },
              { name: "unknownDword15", type: "uint32", defaultValue: 0 },
              { name: "unknownDword16", type: "uint32", defaultValue: 0 },
              { name: "unknownByte6", type: "uint8", defaultValue: 0 },
              { name: "unknownDword17", type: "uint32", defaultValue: 0 },
              { name: "unknownDword18", type: "uint32", defaultValue: 0 },
              { name: "unknownDword19", type: "uint32", defaultValue: 0 },
              { name: "unknownDword20", type: "uint32", defaultValue: 0 },
              { name: "unknownDword21", type: "uint32", defaultValue: 0 },
              { name: "unknownDword22", type: "uint32", defaultValue: 0 },
              { name: "unknownWord13", type: "uint16", defaultValue: 0 },
              { name: "unknownDword23", type: "uint32", defaultValue: 0 },
              { name: "unknownDword24", type: "uint32", defaultValue: 0 },
              { name: "unknownDword25", type: "uint32", defaultValue: 0 },
              { name: "unknownDword26", type: "uint32", defaultValue: 0 },
              { name: "unknownDword27", type: "uint32", defaultValue: 0 },
              { name: "unknownDword28", type: "uint32", defaultValue: 0 },
              { name: "unknownDword29", type: "uint32", defaultValue: 0 },
              { name: "unknownDword30", type: "uint32", defaultValue: 0 },
              { name: "unknownDword31", type: "uint32", defaultValue: 0 },
              { name: "unknownDword32", type: "uint32", defaultValue: 0 },
              { name: "unknownWord14", type: "uint16", defaultValue: 0 },
              { name: "unknownWord15", type: "uint16", defaultValue: 0 },
              { name: "unknownWord16", type: "uint16", defaultValue: 0 },
              { name: "unknownWord17", type: "uint16", defaultValue: 0 },
              { name: "unknownDword33", type: "uint32", defaultValue: 0 },
              {
                name: "unknownDwords1",
                type: "schema",
                defaultValue: {},
                fields: [
                  { name: "unknownDword1", type: "uint32", defaultValue: 0 },
                  { name: "unknownDword2", type: "uint32", defaultValue: 0 },
                  { name: "unknownDword3", type: "uint32", defaultValue: 0 },
                ],
              },
              { name: "unknownByte7", type: "uint8", defaultValue: 0 },
              { name: "unknownDword34", type: "uint32", defaultValue: 0 },
              { name: "unknownDword35", type: "uint32", defaultValue: 0 },
              { name: "unknownWord18", type: "uint16", defaultValue: 0 },
              {
                name: "unknownDwords2",
                type: "schema",
                defaultValue: {},
                fields: [
                  { name: "unknownDword1", type: "uint32", defaultValue: 0 },
                  { name: "unknownDword2", type: "uint32", defaultValue: 0 },
                ],
              },
              {
                name: "unknownDwords3",
                type: "schema",
                defaultValue: {},
                fields: [
                  { name: "unknownDword1", type: "uint32", defaultValue: 0 },
                  { name: "unknownDword2", type: "uint32", defaultValue: 0 },
                ],
              },
              { name: "unknownDword34", type: "uint32", defaultValue: 0 },
              { name: "unknownDword35", type: "uint32", defaultValue: 0 },

              { name: "unknownDword36", type: "uint32", defaultValue: 0 },
              { name: "unknownDword37", type: "uint32", defaultValue: 0 },
              { name: "unknownDword38", type: "uint32", defaultValue: 0 },
              { name: "unknownDword39", type: "uint32", defaultValue: 0 },
              { name: "unknownDword40", type: "uint32", defaultValue: 0 },
              { name: "unknownDword41", type: "uint32", defaultValue: 0 },
              { name: "unknownDword42", type: "uint32", defaultValue: 0 },
              { name: "unknownDword43", type: "uint32", defaultValue: 0 },
              { name: "unknownDword44", type: "uint32", defaultValue: 0 },
              { name: "unknownDword45", type: "uint32", defaultValue: 0 },
              { name: "unknownDword46", type: "uint32", defaultValue: 0 },
              { name: "unknownByte8", type: "uint8", defaultValue: 0 },
              { name: "unknownByte9", type: "uint8", defaultValue: 0 },
              { name: "unknownDword47", type: "uint32", defaultValue: 0 },
              { name: "unknownDword48", type: "uint32", defaultValue: 0 },
              { name: "unknownDword49", type: "uint32", defaultValue: 0 },
              { name: "unknownDword50", type: "uint32", defaultValue: 0 },
              { name: "unknownDword51", type: "uint32", defaultValue: 0 },
              { name: "unknownDword52", type: "uint32", defaultValue: 0 },
              { name: "unknownDword53", type: "uint32", defaultValue: 0 },
              { name: "unknownDword54", type: "uint32", defaultValue: 0 },
              { name: "unknownDword55", type: "uint32", defaultValue: 0 },
              { name: "unknownBoolean1", type: "boolean", defaultValue: false },
              { name: "unknownDword56", type: "uint32", defaultValue: 0 },
              { name: "unknownDword57", type: "uint32", defaultValue: 0 },
              { name: "unknownDword58", type: "uint32", defaultValue: 0 },
              { name: "unknownDword59", type: "uint32", defaultValue: 0 },
              { name: "unknownDword60", type: "uint32", defaultValue: 0 },
              { name: "unknownDword61", type: "uint32", defaultValue: 0 },
              { name: "unknownDword62", type: "uint32", defaultValue: 0 },
              { name: "unknownBoolean2", type: "boolean", defaultValue: false },
              { name: "unknownDword63", type: "uint32", defaultValue: 0 },
              { name: "unknownDword64", type: "uint32", defaultValue: 0 },
              { name: "unknownDword65", type: "uint32", defaultValue: 0 },
              { name: "unknownDword66", type: "uint32", defaultValue: 0 },
              { name: "unknownDword67", type: "uint32", defaultValue: 0 },
              { name: "unknownDword68", type: "uint32", defaultValue: 0 },
              { name: "unknownDword69", type: "uint32", defaultValue: 0 },
              { name: "unknownDword70", type: "uint32", defaultValue: 0 },
              { name: "unknownDword71", type: "uint32", defaultValue: 0 },
              { name: "unknownDword72", type: "uint32", defaultValue: 0 },
              { name: "unknownDword73", type: "uint32", defaultValue: 0 },
              { name: "unknownDword74", type: "uint32", defaultValue: 0 },
              { name: "unknownDword75", type: "uint32", defaultValue: 0 },
              { name: "unknownDword76", type: "uint32", defaultValue: 0 },
              { name: "unknownDword77", type: "uint32", defaultValue: 0 },
              { name: "unknownDword78", type: "uint32", defaultValue: 0 },
              { name: "unknownDword79", type: "uint32", defaultValue: 0 },
              { name: "unknownDword80", type: "uint32", defaultValue: 0 },
              { name: "unknownDword81", type: "uint32", defaultValue: 0 },
              { name: "unknownDword82", type: "uint32", defaultValue: 0 },
              { name: "unknownDword83", type: "uint32", defaultValue: 0 },
              { name: "unknownDword84", type: "uint32", defaultValue: 0 },
              { name: "unknownDword85", type: "uint32", defaultValue: 0 },
              { name: "unknownDword86", type: "uint32", defaultValue: 0 },
              { name: "unknownDword87", type: "uint32", defaultValue: 0 },
              { name: "unknownDword88", type: "uint32", defaultValue: 0 },
              { name: "unknownDword89", type: "uint32", defaultValue: 0 },
              { name: "unknownDword90", type: "uint32", defaultValue: 0 },
              { name: "unknownDword91", type: "uint32", defaultValue: 0 },
              { name: "unknownDword92", type: "uint32", defaultValue: 0 },
              { name: "unknownDword93", type: "uint32", defaultValue: 0 },
              { name: "unknownDword94", type: "uint32", defaultValue: 0 },
              { name: "unknownDword95", type: "uint32", defaultValue: 0 },
              { name: "unknownDword96", type: "uint32", defaultValue: 0 },
              { name: "unknownDword97", type: "uint32", defaultValue: 0 },
              { name: "unknownDword98", type: "uint32", defaultValue: 0 },
              { name: "unknownDword99", type: "uint32", defaultValue: 0 },
              { name: "unknownDword100", type: "uint32", defaultValue: 0 },
              { name: "unknownDword101", type: "uint32", defaultValue: 0 },
              { name: "unknownDword102", type: "uint32", defaultValue: 0 },
              { name: "unknownDword103", type: "uint32", defaultValue: 0 },
              { name: "unknownDword104", type: "uint32", defaultValue: 0 },
              { name: "unknownDword105", type: "uint32", defaultValue: 0 },
              { name: "unknownDword106", type: "uint32", defaultValue: 0 },
              { name: "unknownBoolean3", type: "boolean", defaultValue: false },
              { name: "unknownDword107", type: "uint32", defaultValue: 0 },
              { name: "unknownBoolean4", type: "boolean", defaultValue: false },
              { name: "unknownDword108", type: "uint32", defaultValue: 0 },
              { name: "unknownDword109", type: "uint32", defaultValue: 0 },
              { name: "unknownDword110", type: "uint32", defaultValue: 0 },
              { name: "unknownDword111", type: "uint32", defaultValue: 0 },
              { name: "unknownDword112", type: "uint32", defaultValue: 0 },
              { name: "unknownDword113", type: "uint32", defaultValue: 0 },
              { name: "unknownDword114", type: "uint32", defaultValue: 0 },
              { name: "unknownDword115", type: "uint32", defaultValue: 0 },
              { name: "unknownDword116", type: "uint32", defaultValue: 0 },
              { name: "unknownDword117", type: "uint32", defaultValue: 0 },
              { name: "unknownDword118", type: "uint32", defaultValue: 0 },
              { name: "unknownDword119", type: "uint32", defaultValue: 0 },
              { name: "unknownBoolean5", type: "boolean", defaultValue: false },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "unknownArray4",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      { name: "unknownDword1", type: "uint32", defaultValue: 0 },
      {
        name: "unknownArray1",
        type: "array",
        defaultValue: [],
        fields: [
          { name: "unknownDword1", type: "uint32", defaultValue: 0 },
          {
            name: "unknownData1",
            type: "schema",
            defaultValue: {},
            fields: [
              { name: "unknownDword1", type: "uint32", defaultValue: 0 },
              { name: "unknownByte1", type: "uint8", defaultValue: 0 },
              { name: "unknownDword2", type: "uint32", defaultValue: 0 },
              { name: "unknownDword3", type: "uint32", defaultValue: 0 },
              { name: "unknownDword4", type: "uint32", defaultValue: 0 },
              { name: "unknownDword5", type: "uint32", defaultValue: 0 },
              { name: "unknownDword6", type: "uint32", defaultValue: 0 },
              { name: "unknownDword7", type: "uint32", defaultValue: 0 },
              { name: "unknownDword8", type: "uint32", defaultValue: 0 },
              { name: "unknownDword9", type: "uint32", defaultValue: 0 },
              { name: "unknownDword10", type: "uint32", defaultValue: 0 },
              { name: "unknownDword11", type: "uint32", defaultValue: 0 },
              { name: "unknownDword12", type: "uint32", defaultValue: 0 },
              { name: "unknownDword13", type: "uint32", defaultValue: 0 },
              { name: "unknownDword14", type: "uint32", defaultValue: 0 },
              { name: "unknownDword15", type: "uint32", defaultValue: 0 },
              { name: "unknownDword16", type: "uint32", defaultValue: 0 },
              { name: "unknownDword17", type: "uint32", defaultValue: 0 },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "unknownArray5",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "unknownData1",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "unknownDword1", type: "uint32", defaultValue: 0 },
          { name: "unknownDword2", type: "uint32", defaultValue: 0 },
          { name: "unknownDword3", type: "uint32", defaultValue: 0 },
        ],
      },
    ],
  },
  {
    name: "unknownArray6",
    type: "array",
    defaultValue: [],
    fields: [
      { name: "ID", type: "uint32", defaultValue: 0 },
      {
        name: "unknownData1",
        type: "schema",
        defaultValue: {},
        fields: [
          { name: "unknownDword1", type: "uint32", defaultValue: 0 },
          { name: "unknownDword2", type: "uint32", defaultValue: 0 },
          { name: "unknownDword3", type: "uint32", defaultValue: 0 },
          { name: "unknownDword4", type: "uint32", defaultValue: 0 },
          { name: "unknownDword5", type: "uint32", defaultValue: 0 },
          { name: "unknownDword6", type: "uint32", defaultValue: 0 },
          { name: "unknownDword7", type: "uint32", defaultValue: 0 },
          { name: "unknownDword8", type: "uint32", defaultValue: 0 },
          { name: "unknownDword9", type: "uint32", defaultValue: 0 },
          { name: "unknownDword10", type: "uint32", defaultValue: 0 },
          { name: "unknownDword11", type: "uint32", defaultValue: 0 },
          { name: "unknownDword12", type: "uint32", defaultValue: 0 },
          { name: "unknownDword13", type: "uint32", defaultValue: 0 },
          { name: "unknownDword14", type: "uint32", defaultValue: 0 },
          { name: "unknownDword15", type: "uint32", defaultValue: 0 },
          { name: "unknownDword16", type: "uint32", defaultValue: 0 },
          { name: "unknownDword17", type: "uint32", defaultValue: 0 },
          { name: "unknownDword18", type: "uint32", defaultValue: 0 },
          { name: "unknownDword19", type: "uint32", defaultValue: 0 },
          { name: "unknownDword20", type: "uint32", defaultValue: 0 },
          { name: "unknownDword21", type: "uint32", defaultValue: 0 },
          { name: "unknownDword22", type: "uint32", defaultValue: 0 },
          { name: "unknownDword23", type: "uint32", defaultValue: 0 },
        ],
      },
    ],
  },
];

function packWeaponDefinitionData(obj: any) {
  let compressionData = Buffer.allocUnsafe(8);
  const data = DataSchema.pack(
    weaponDefinitionSchema,
    obj
  ).data,
  input = data;
  let output = Buffer.alloc(LZ4.encodeBound(input.length));
  output = output.slice(0, LZ4.encodeBlock(input, output));
  compressionData.writeUInt32LE(output.length, 0);
  compressionData.writeUInt32LE(data.length, 4);
  return Buffer.concat([compressionData, output]);
}

export const referenceDataPackets: any = [
  ["ReferenceData.ItemClassDefinitions", 0x1701, {}],
  ["ReferenceData.ItemCategoryDefinitions", 0x1702, {}],
  [
    "ReferenceData.ClientProfileData",
    0x1703,
    {
      fields: [
        {
          name: "profiles",
          type: "array",
          defaultValue: [],
          fields: profileDataSchema,
        },
      ],
    },
  ],
  [
    "ReferenceData.WeaponDefinitions",
    0x1704,
    {
      fields: [
        {
          name: "data",
          type: "byteswithlength",
          fields: [
            {
              name: "definitionsData",
              type: "custom",
              packer: packWeaponDefinitionData,
            },
          ],
        },
      ],
    },
  ],
  ["ReferenceData.ProjectileDefinitions", 0x1705, {}],
  [
    "ReferenceData.VehicleDefinitions",
    0x1706,
    {
      fields: [
        {
          name: "data",
          type: "custom",
          parser: parseVehicleReferenceData,
          packer: packVehicleReferenceData,
        },
      ],
    },
  ],
];
