name: test-binaries
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

jobs:
  test-binaries:
    name: Test Binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.9.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.9.0
      - run: npm i --production
      - run: npm i -g pkg@5.3.1
      - run: pkg -t node16-win-x64 ./bin/2015/h1emuServer.js --output ./bin/h1emuServer-${{ github.ref }}.exe
      - run: pkg -t node16-win-x64 ./bin/2016/h1emuServer.js --output ./bin/h1emuServer-2016-${{ github.ref }}.exe
      - run: ./bin/h1emuServer-${{ github.ref }}.exe --test
      - run: ./bin/h1emuServer-2016-${{ github.ref }}.exe --test
